<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crud.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string receipt_number = 2;</code>
     */
    protected $receipt_number = '';
    /**
     * Generated from protobuf field <code>string bus = 3;</code>
     */
    protected $bus = '';
    /**
     * Generated from protobuf field <code>string route_from = 4;</code>
     */
    protected $route_from = '';
    /**
     * Generated from protobuf field <code>string route_to = 5;</code>
     */
    protected $route_to = '';
    /**
     * Generated from protobuf field <code>string schedule = 6;</code>
     */
    protected $schedule = '';
    /**
     * Generated from protobuf field <code>string trip = 7;</code>
     */
    protected $trip = '';
    /**
     * Generated from protobuf field <code>string num_tickets = 8;</code>
     */
    protected $num_tickets = '';
    /**
     * Generated from protobuf field <code>string price = 9;</code>
     */
    protected $price = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $receipt_number
     *     @type string $bus
     *     @type string $route_from
     *     @type string $route_to
     *     @type string $schedule
     *     @type string $trip
     *     @type string $num_tickets
     *     @type string $price
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Crud::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string receipt_number = 2;</code>
     * @return string
     */
    public function getReceiptNumber()
    {
        return $this->receipt_number;
    }

    /**
     * Generated from protobuf field <code>string receipt_number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiptNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->receipt_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bus = 3;</code>
     * @return string
     */
    public function getBus()
    {
        return $this->bus;
    }

    /**
     * Generated from protobuf field <code>string bus = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBus($var)
    {
        GPBUtil::checkString($var, True);
        $this->bus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string route_from = 4;</code>
     * @return string
     */
    public function getRouteFrom()
    {
        return $this->route_from;
    }

    /**
     * Generated from protobuf field <code>string route_from = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRouteFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->route_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string route_to = 5;</code>
     * @return string
     */
    public function getRouteTo()
    {
        return $this->route_to;
    }

    /**
     * Generated from protobuf field <code>string route_to = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRouteTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->route_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schedule = 6;</code>
     * @return string
     */
    public function getSchedule()
    {
        return $this->schedule;
    }

    /**
     * Generated from protobuf field <code>string schedule = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSchedule($var)
    {
        GPBUtil::checkString($var, True);
        $this->schedule = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trip = 7;</code>
     * @return string
     */
    public function getTrip()
    {
        return $this->trip;
    }

    /**
     * Generated from protobuf field <code>string trip = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTrip($var)
    {
        GPBUtil::checkString($var, True);
        $this->trip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string num_tickets = 8;</code>
     * @return string
     */
    public function getNumTickets()
    {
        return $this->num_tickets;
    }

    /**
     * Generated from protobuf field <code>string num_tickets = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNumTickets($var)
    {
        GPBUtil::checkString($var, True);
        $this->num_tickets = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string price = 9;</code>
     * @return string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>string price = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->price = $var;

        return $this;
    }

}

